services:
  mongodb:
    container_name: ms_nosql_mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=local
      - MONGO_INITDB_ROOT_PASSWORD=local
    volumes:
      - mongo:/data
    ports:
      - 27017:27017
  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=local
      - ME_CONFIG_MONGODB_ADMINPASSWORD=local
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=local
      - ME_CONFIG_BASICAUTH_PASSWORD=local
    ports:
      - 8081:8081
    restart: unless-stopped
  rabbitmq:
    container_name: ms_rabbitmq
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/
volumes:
  mongo: